<?php

class Easyship_Shipping_Block_Adminhtml_Config_Connect extends Mage_Adminhtml_Block_System_Config_Form_Fieldset
{
    public function render(Varien_Data_Form_Element_Abstract $element)
    {
        //return parent::render($element); // TODO: Change the autogenerated stub

        $html = $this->_getHeaderHtml($element);

        $setupready = false;
        $collection = Mage::getModel('oauth/consumer')->getCollection();


        foreach ($collection as $consumer) {
            if ($consumer->getName() == 'easyship') {
                $setupready = true;
                break;
            }
        }

        if ($setupready) {
            $html .= $this->_getAciveFieldHtml($element);
            foreach (Mage::app()->getWebsites() as $website) {
                foreach ($website->getGroups() as $webgroup) {
                    $stores = $webgroup->getStores();
                    foreach ($stores as $store) {
                        $html .= $this->_getFieldHtml($element, $store);
                    }
                }
            }
        } else {
            $html .= $this->getInstruction();
        }


        $html .= $this->_getFooterHtml($element);

        return $html;

    }

    protected function getInstruction()
    {
        $html = '
                  <h3>Easyship Plugin Setup Requirement</h3>
                 <div style="color:red; margin: 5px 0px;">OAuth Consumer named <strong> easyship</strong> is not found.  It is required to allow Easyship to retrieve information with Magento REST API. Please follow the instruction to setup your 
                 Easyship OAuth consumer.</div>
                 
                 <div style="display:block; background-color: white; border: 1px solid black; padding: 5px 10px;"> Please go to <a href="https://www.easyship.com" target="_blank">https://www.easyship.com</a> for setup instruction.</div>
                
                ';
        return $html;

    }

    protected function _getFieldRenderer()
    {
        if (empty($this->_fieldRenderer)) {
            $this->_fieldRenderer = Mage::getBlockSingleton('easyship/adminhtml_config_generate');
        }
        return $this->_fieldRenderer;
    }

    protected function _getValues()
    {
        if (empty($this->_values)) {
            $this->_values = array(
                array('label'=>Mage::helper('adminhtml')->__('No'), 'value'=>0),
                array('label'=>Mage::helper('adminhtml')->__('Yes'), 'value'=>1),
            );
        }
        return $this->_values;
    }

    protected function _getAciveFieldHtml($fieldset)
    {
        $configData = $this->getConfigData();

        $path = 'easyship_options/ec_shipping/active';

        if (isset($configData[$path])) {
            // access token is enabled
            $data = $configData[$path];
            $inherit = false;
        }
        else {
            $data = $this->getForm()->getConfigRoot()->descend($path);
            $inherit = true;
        }

        $field = $fieldset->addField('active', 'select',
            array(
                'name'  => 'groups[ec_shipping][fields][active][value]',
                'label' => 'Enable',
                'value' => $data,
                'values' => $this->_getValues(),
                'inherit' => $inherit

            ))->setRenderer( Mage::getBlockSingleton('adminhtml/system_config_form_field'));


        return $field->toHtml();
    }


    protected function _getFieldHtml($fieldset, Mage_Core_Model_Store $store)
    {
        $configData = $this->getConfigData();

        // config data for store
        // access token that retrieve from Easyship
        $path = 'easyship_options/ec_shipping/store_' . $store->getId();
        if (isset($configData[$path])) {
            // access token is enabled
            $data = $configData[$path];
            $inherit = false;
        }
        else {
            $data = $this->getForm()->getConfigRoot()->descend($path);
            $inherit = true;
        }

        $field = $fieldset->addField($store->getId(), 'text',
            array(
                'name'  => 'groups[ec_shipping][fields][store_'.$store->getId().'][value]',
                'label' => $store->getFrontendName(),
                'value' => $data,
                'inherit' => $inherit,
                'storeid' => $store->getId()

            ))->setRenderer($this->_getFieldRenderer());


        return $field->toHtml();

    }




}