<?php
/**
 * Class Easyship_Shipping_Block_Adminhtml_Config_Generate
 * Author: Easyship
 * Developer: Sunny Cheung, Aloha Chen, Phanarat Pak, Paul Lugangne Delpon
 * Version: 0.1.0
 * Author URI: https://www.easyship.com
*/

class Easyship_Shipping_Block_Adminhtml_Config_Generate extends Mage_Adminhtml_Block_System_Config_Form_Field
{

    /**
     * Constructor
     */
    protected function _construct()
    {
        parent::_construct();
        $this->setTemplate('easyship/system/config/generate.phtml');
    }

    /**
     * Prepare Layout for the field
     *
     * @return Mage_Adminhtml_Block_System_Config_Form_Field
     */
    protected function _prepareLayout()
    {
        parent::_prepareLayout(); // TODO: Change the autogenerated stub
        if (!$this->getTemplate()) {
            $this->setTemplate('easyship/system/config/generate.phtml');
        }
        return $this;
    }

    /**
     * Render function for the Field
     *
     * @param Vairen_Data_Form_element_Abstract
     * @return string
     */
    public function render(Varien_Data_Form_Element_Abstract $element)
    {

        $id = $element->getHtmlId();

        $html = '<td><div id="easyship">';

        $html .= $this->_getElementHtml($element);

        $html .= '</div></td>';
        if ($addInheritCheckbox) {

            $defText = $element->getDefaultValue();
            if ($options) {
                $defTextArr = array();
                foreach ($options as $k=>$v) {
                    if ($isMultiple) {
                        if (is_array($v['value']) && in_array($k, $v['value'])) {
                            $defTextArr[] = $v['label'];
                        }
                    } elseif (isset($v['value'])) {
                        if ($v['value'] == $defText) {
                            $defTextArr[] = $v['label'];
                            break;
                        }
                    } elseif (!is_array($v)) {
                        if ($k == $defText) {
                            $defTextArr[] = $v;
                            break;
                        }
                    }
                }
                $defText = join(', ', $defTextArr);
            }

            // default value
            $html.= '<td class="use-default">';
            $html.= '<input id="' . $id . '_inherit" name="'
                . $namePrefix . '[inherit]" type="checkbox" value="1" class="checkbox config-inherit" '
                . $inherit . ' onclick="toggleValueElements(this, Element.previous(this.parentNode))" /> ';
            $html.= '<label for="' . $id . '_inherit" class="inherit" title="'
                . htmlspecialchars($defText) . '">' . $checkboxLabel . '</label>';
            $html.= '</td>';
        }

        $html.= '<td class="scope-label">';
        if ($element->getScope()) {
            $html .= $element->getScopeLabel();
        }
        $html.= '</td>';

        $html.= '<td class="">';
        if ($element->getHint()) {
            $html.= '<div class="hint" >';
            $html.= '<div style="display: none;">' . $element->getHint() . '</div>';
            $html.= '</div>';
        }
        $html.= '</td>';

        return $this->_decorateRowHtml($element, $html);
    }


    /**
     * populate configuration data to HTML
     *
     * @param Vairen_Data_From_Element_Abstract
     * @return string
     */
    protected function _getElementHtml(Varien_Data_Form_Element_Abstract $element)
    {

        $id = $element->getStoreid();
        $is_actived = Mage::getStoreConfig('easyship_options/ec_shipping/store_' . $id . '_isExtActive', 0);
        $is_enabled = Mage::getStoreConfig('easyship_options/ec_shipping/store_' . $id . '_isRateEnabled', 0);
        $url = Mage::helper( 'adminhtml')->getUrl('adminhtml/easyship/ajaxregister');
        $enable_rate_url = Mage::helper('adminhtml')->getUrl('adminhtml/easyship/ajaxactivate');
        $disable_rate_url = Mage::helper('adminhtml')->geturl('adminhtml/easyship/ajaxdeactivate');
        $reset_url = Mage::helper('adminhtml')->getUrl('adminhtml/easyship/ajaxresetstore');
        $this->addData(
            array(
                'store' => $element->getLabel(),
                'storeid' => $id,
                'enabled' => $is_enabled,
                'actived' => $is_actived,
                'storeurl' => $url,
                'acturl' => $enable_rate_url,
                'deacturl' => $disable_rate_url,
                'resetstoreurl' => $reset_url
                
            )
        );

        return $this->_toHtml();
    }


}
